"""Greedy meshing for voxel chunks.

This module implements a CPU-based greedy meshing algorithm for voxel data.
The implementation follows the approach described in
https://0fps.net/2012/06/30/meshing-in-a-minecraft-game/ and generates
contiguous quads for visible faces only.  The resulting vertices and indices
can be uploaded directly to GPU buffers.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import List, Tuple

import numpy as np


@dataclass
class MeshBuffers:
    """Container for mesh data generated by :func:`greedy_mesh`.

    Attributes
    ----------
    vertices:
        Array of vertex positions ``(N, 3)`` as ``float32``.
    indices:
        Triangle index buffer as ``uint32`` with ``3 * T`` entries.
    """

    vertices: np.ndarray
    indices: np.ndarray


def greedy_mesh(voxels: np.ndarray) -> MeshBuffers:
    """Generate a greedy mesh for the given voxel volume.

    Parameters
    ----------
    voxels:
        3-D ``numpy`` array with non-zero values marking solid voxels.

    Returns
    -------
    MeshBuffers
        Vertices and indices describing the mesh.
    """

    assert voxels.ndim == 3, (
        f"Voxel data must be a 3-D array with shape (width, height, depth). "
        f"Received array with shape {voxels.shape}."
    )
    dims = voxels.shape

    vertices: List[float] = []
    indices: List[int] = []

    def add_quad(origin: np.ndarray, du: np.ndarray, dv: np.ndarray, sign: int) -> None:
        base = len(vertices) // 3
        quad = [
            origin,
            origin + du,
            origin + du + dv,
            origin + dv,
        ]
        for v in quad:
            vertices.extend(v.tolist())
        if sign > 0:
            indices.extend([base, base + 1, base + 2, base, base + 2, base + 3])
        else:
            indices.extend([base, base + 2, base + 1, base, base + 3, base + 2])

    # Iterate over each principal axis
    for d in range(3):
        u, v = (d + 1) % 3, (d + 2) % 3
        q = np.zeros(3, dtype=int)
        q[d] = 1

        for slice_ in range(-1, dims[d]):
            # Build a 2-D mask of the faces between slice and slice+1
            mask = np.zeros((dims[u], dims[v]), dtype=int)
            for x in range(dims[u]):
                for y in range(dims[v]):
                    a = 0
                    b = 0
                    pos = [0, 0, 0]
                    pos[u] = x
                    pos[v] = y
                    pos[d] = slice_
                    if 0 <= slice_ < dims[d]:
                        a = int(voxels[tuple(pos)])
                    pos[d] = slice_ + 1
                    if 0 <= slice_ + 1 < dims[d]:
                        b = int(voxels[tuple(pos)])
                    if bool(a) != bool(b):
                        mask[x, y] = 1 if a else -1

            # Greedily merge rectangles in the mask
            j = 0
            while j < mask.shape[1]:
                i = 0
                while i < mask.shape[0]:
                    c = mask[i, j]
                    if c != 0:
                        w = 1
                        while i + w < mask.shape[0] and mask[i + w, j] == c:
                            w += 1
                        h = 1
                        done = False
                        while j + h < mask.shape[1]:
                            for k in range(w):
                                if mask[i + k, j + h] != c:
                                    done = True
                                    break
                            if done:
                                break
                            h += 1
                        origin = np.zeros(3, dtype=float)
                        origin[u] = i
                        origin[v] = j
                        origin[d] = slice_ + (1 if c > 0 else 0)
                        du = np.zeros(3, dtype=float)
                        du[u] = w
                        dv = np.zeros(3, dtype=float)
                        dv[v] = h
                        add_quad(origin, du, dv, c)
                        for l in range(h):
                            for k in range(w):
                                mask[i + k, j + l] = 0
                        i += w
                    else:
                        i += 1
                j += 1

    v_array = np.array(vertices, dtype=np.float32).reshape(-1, 3)
    i_array = np.array(indices, dtype=np.uint32)
    return MeshBuffers(vertices=v_array, indices=i_array)


__all__ = ["MeshBuffers", "greedy_mesh"]

