name: CMake

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ~/.cache
          key: ${{ runner.os }}-cmake-${{ hashFiles('**/CMakeLists.txt') }}
      - uses: lukka/get-cmake@v3
      - uses: seanmiddleditch/gha-setup-ninja@v4
      - name: Configure
        run: cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=RelWithDebInfo
      - name: Build
        run: cmake --build build -j
      - name: Test
        run: ctest --test-dir build --output-on-failure

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ~\AppData\Local\cache
          key: ${{ runner.os }}-cmake-${{ hashFiles('**/CMakeLists.txt') }}
      - uses: lukka/get-cmake@v3
      - uses: seanmiddleditch/gha-setup-ninja@v4
      - name: Configure
        run: cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=RelWithDebInfo
      - name: Build
        run: cmake --build build -j
      - name: Test
        run: ctest --test-dir build --output-on-failure
