name: CMake

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: |
            build/bin/**
            build/spv/**
          key: ${{ runner.os }}-cmake-${{ hashFiles('**/CMakeLists.txt') }}
      - name: Install deps
        run: sudo apt-get update && sudo apt-get install -y ninja-build cmake g++
      - name: Configure
        run: cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=RelWithDebInfo
      - name: Build
        run: cmake --build build -j
      - name: Test
        run: ctest --test-dir build --output-on-failure

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: |
            build/bin/**
            build/spv/**
          key: ${{ runner.os }}-cmake-${{ hashFiles('**/CMakeLists.txt') }}
      - name: Install Ninja and CMake
        run: choco install ninja cmake --yes
      - name: Configure
        run: cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=RelWithDebInfo
      - name: Build
        run: cmake --build build -j
      - name: Test
        run: ctest --test-dir build --output-on-failure
